### PR TITLE
Updated package dependencies to latest one

### PR DESCRIPTION
**Pull request by sgnn7**
We had warnings on GH about outdated dependencies with security issues
so we have updated them.

### CODE REVIEW

**Comment by ptomato** [comment]
I think you have to update the commit hash in the manifest in flathub/com.endlessm.HatchPreviewer in order to release a new version on Flathub.

**Comment by manuq** [comment]
@ptomato yes, I will do it.

**Comment by manuq** [comment]
@ptomato @sgnn7 hmm, actually I think this PR was wrong, it removed the `package-lock.json` and we agreed on keeping it. Sorry, my review wasn't good, I will create a new PR with the lock file back.

**Comment by sgnn7** [comment]
@manuq I thought I updated it, not removed it but I did have some npm issues doing an `npm install` that I might have accidentally checked in.... 
Sorry about that - I really didn't mean to get it deleted.

**Comment by manuq** [comment]
@sgnn7 no problem, yes I assumed it was by accident as the commit message didn't  say anything about a removed file. Also, the flathub package needs to generate a JSON from this lock file. PR coming.

**Pull request merged**
